apiVersion: apps/v1
kind: Deployment
metadata:
  name: album-viewer-db
  labels:
    app: album-viewer-db
spec:
  replicas: 1
  template:
    metadata:
      name: album-viewer-db
      labels:
        app: album-viewer-db
    spec:
      containers:
      - name: album-viewer-db
        image: dockersamples/tidb:nanoserver-1809
        ports:
        - containerPort: 3306
          protocol: TCP
      nodeSelector:
        kubernetes.io/os: windows
      schedulerName: default-scheduler
      serviceAccount: default
      serviceAccountName: default
      restartPolicy: Always
  selector:
    matchLabels:
      app: album-viewer-db