apiVersion: v1
kind: Service
metadata:
  name: album-viewer-db-svc
  labels:
    app: album-viewer-db-svc
spec:
  ports:
    # the port that this service should serve on
    - port: 3306
      targetPort: 3306
  selector:
    app: album-viewer-db-svc
  type: NodePort