apiVersion: apps/v1
kind: Deployment
metadata:
  name: album-viewer
  labels:
    app: album-viewer
spec:
  replicas: 1
  template:
    metadata:
      name: album-viewer
      labels:
        app: album-viewer
    spec:
      containers:
      - name: album-viewer
        image: 35.222.125.50:8624/vmie-dev/library/albumviewer:albumviewer
        ports:
        - containerPort: 80
          protocol: TCP
      nodeSelector:
        kubernetes.io/os: windows
      schedulerName: default-scheduler
      serviceAccount: default
      serviceAccountName: default
      restartPolicy: Always
  selector:
    matchLabels:
      app: album-viewer