apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-album-viewer
  labels:
    app: nginx-album-viewer
spec:
  replicas: 1
  template:
    metadata:
      name: nginx-album-viewer
      labels:
        app: nginx-album-viewer
    spec:
      containers:
      - name: nginx-album-viewer
        image: 35.224.56.220:8624/vmie-dev/library/nginxalbumviewer:nginxalbumviewer
        ports:
        - containerPort: 80
          protocol: TCP
      nodeSelector:
        kubernetes.io/os: linux
      schedulerName: default-scheduler
      serviceAccount: default
      serviceAccountName: default
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx-album-viewer