apiVersion: v1
kind: Service
metadata:
  name: album-viewer-svc
  labels:
    app: album-viewer-svc
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: album-viewer-svc
  type: NodePort